### ISSUE TITLE
Is there Swift 2.0 support?

### ISSUE THREAD

**Issue by samuelbeek** [gmertk/ParkedTextField#13]

**Comment by chrisballinger** [comment]
Not yet, but if someone hasn't started working on it already, I can fix the current compilation errors and submit a PR.

@gmertk Will you be available within the next week to merge a PR with Swift 2.0 support?

**Comment by chrisballinger** [comment]
Looks like @remzr7 started working on it over here: https://github.com/remzr7/ParkedTextField/commit/b79adc59b208dbf78fe43cb30d8bd977da848429

I'd probably learn towards not using `!` in so many places though.

**Comment by gmertk** [comment]
Sure I can merge a proper PR! :+1:

**Comment by chrisballinger** [comment]
@gmertk PR submitted!
