### ISSUE TITLE
Carthage support...

### ISSUE THREAD

**Issue by istx25** [gmertk/ParkedTextField#7]
Let's add Carthage support! It is the future! :wink: The most efficient way to do this is to create a new framework project with the Swift class and a _Single View Project_ target for the sample project to reduce project size. What do you guys think?

**Comment by gmertk** [comment]
Sure I will check it out this weekend. Haven't used Carthage before, but obviously it is getting popular. 

Also don't hesitate to send a pull request.

**Comment by istx25** [comment]
@gmertk Check out #8. :heart:

**Comment by gmertk** [comment]
@istx25 thanks for the PR!

**Comment by istx25** [comment]
My pleasure.
